const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const request = require('supertest');
const app = require('./server');
const env = require('./config/env');
const User = require('./models/User');
const Scan = require('./models/Scan');
const EmailHistory = require('./models/EmailHistory');
const emailHistoryService = require('./services/emailHistoryService');

async function runTests() {
  console.log("Waiting for DB to connect...");
  await new Promise(resolve => setTimeout(resolve, 1500));

  await User.deleteMany({});
  await Scan.deleteMany({});
  await EmailHistory.deleteMany({});

  const userA = await User.create({ name: 'User A', email: 'a@test.com', password: 'password123' });
  const userB = await User.create({ name: 'User B', email: 'b@test.com', password: 'password123' });

  const tokenA = jwt.sign({ id: userA._id }, env.JWT_SECRET, { expiresIn: '1h' });
  const authA = `Bearer ${tokenA}`;

  // Pre-populate some email history for User A
  console.log("Pre-populating historical emails for User A...");
  await emailHistoryService.createEmailHistory(userA._id, { sender: 'boss@company.com', recipient: 'a@test.com', subject: 'Report', body: 'Please send the quarterly report.' });
  await emailHistoryService.createEmailHistory(userA._id, { sender: 'it@company.com', recipient: 'a@test.com', subject: 'Password', body: 'Your password expires in 30 days.' });
  
  // Wait a moment for async embedding to finish in python if running
  await new Promise(resolve => setTimeout(resolve, 2000));

  console.log("--- Starting Pipeline Tests ---");

  try {
    console.log("1. Testing Email Scan with Historical RAG Context (User A)...");
    
    // Simulating a spear-phishing attack. The sender is similar but domain is different.
    const resScanA = await request(app)
      .post('/api/scan')
      .set('Authorization', authA)
      .send({ 
        scanType: 'email', 
        content: 'From: boss@c0mpany.com\nTo: a@test.com\nSubject: Report\nBody: Please send the quarterly report immediately to this new address.' 
      });
    
    if (resScanA.status !== 200) throw new Error("Scan failed: " + JSON.stringify(resScanA.body));
    const scanResult = resScanA.body.data.result;
    
    console.log(`Scan Result: ${scanResult.classification} (Score: ${scanResult.riskScore})`);
    if (scanResult.rag && scanResult.rag.status === 'available') {
      console.log(`=> RAG successfully retrieved ${scanResult.rag.retrievedEmails.length} historical emails.`);
      if (scanResult.rag.retrievedEmails.length === 0) {
        throw new Error("RAG did not retrieve historical emails.");
      }
    } else {
      throw new Error("RAG status is not available.");
    }

    // Verify personalization evidence exists (LLM should point out the domain mismatch)
    const hasPersonalization = scanResult.reasons.some(r => r.title && r.title.includes('Personalization'));
    if (!hasPersonalization) {
      console.log("WARNING: LLM did not generate personalization evidence. This might depend on Groq's exact response, but checking...");
    } else {
      console.log("=> RAG personalization evidence was successfully generated by LLM.");
    }

    console.log("2. Testing URL Scan with PhishDestroy...");
    // PhishDestroy logic in current mock or real logic might flag bad URLs. Let's use a known bad url if we mock, or just any url.
    const resScanUrl = await request(app)
      .post('/api/scan')
      .set('Authorization', authA)
      .send({ scanType: 'url', content: 'http://malicious-test-phish.com' });
    
    if (resScanUrl.status !== 200) throw new Error("URL Scan failed");
    console.log(`URL Scan Result: ${resScanUrl.body.data.result.classification}`);
    
    // Check if RAG was properly skipped for URL
    if (resScanUrl.body.data.result.rag) {
       throw new Error("RAG should not be executed for URL scans.");
    } else {
       console.log("=> RAG correctly skipped for URL scan.");
    }

    console.log("3. Verifying Scan Model Storage...");
    const scans = await Scan.find({ user: userA._id });
    console.log(`=> Found ${scans.length} scans saved in DB for User A.`);
    if (scans.length < 2) throw new Error("Scans not saved correctly.");
    
    console.log("ALL PIPELINE TESTS PASSED!");
  } catch (err) {
    console.error("TEST FAILED:", err);
  } finally {
    process.exit(0);
  }
}

runTests();
